# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Open Educational Resource
    local_business_type: ''
    org_name: 'Weecology'
    summary: 'Open education resource and lesson material for learning ecological forecasting.'
    twitter: 'weecology'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: 'Â© {year} Contributors and the University of Florida. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: false
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/weecology/forecasting-course'
    content_dir: content
    branch: main
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/<USERNAME>/<REPO>/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/<USERNAME>/<REPO>/issues/new).'
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
